### ISSUE TITLE
Remove explicit support for targeting view instances

### ISSUE THREAD

**Issue by lindem** [yapplabs/ember-modal-dialog#121]
Currently, there is a deprecation warning because this addon uses ember-legacy-views.

I did not find an issue regarding this, so I opened one. Are there already plans to remedy this?

**Comment by chrislopresto** [comment]
@lindem I suppose it is time to remove explicit view-related support. We included `ember-legacy-views` to maintain tests for positioning modals relative to view instances.

I won't have any time until at least after EmberConf, but we would certainly accept a PR for this.

Thanks for opening the issue.

**Comment by maxwerr** [comment]
@chrislopresto does this just involve removing the view-related tests/helper references (thereby not really supporting views anymore)?

**Comment by rwjblue** [comment]
The usage of ember-legacy-views is breaking against Ember 2.6 and higher (since `{{view` helper is not present even with the addon in those versions), but `config/ember-try.js` doesn't include 2.5/2.6/2.7 so it doesn't show up in CI builds.  I noticed this while trying to run the test suite against the current alpha (for glimmer2 compat).

**Comment by Vincz** [comment]
Any update on this ? :)

**Comment by maxwerr** [comment]
In my pr, above, suggestion was to modify `target` and `targetElement` with a component instead of removing them with others... not sure how close I'll get but I'd be happy to try moar soon.

**Comment by lukemelia** [comment]
View support is being dropped in #172, which will be released as 2.0.0.
