### ISSUE TITLE
 Ember v3.27: Exception on Ember.computed.reads (liquid-wormhole)

### ISSUE THREAD

**Issue by ptgamr** [yapplabs/ember-modal-dialog#336]
After upgrade to Ember 3.27, I got error like this and the modal is not showing, it's related to the `liquid-*` packages:

```
Uncaught TypeError: Ember.computed.reads is not a function
    at Module.callback (liquid-wormhole.js:10)
```

I am not sure how to fix this, I think the deprecation of Global Ember https://github.com/emberjs/rfcs/blob/master/text/0706-deprecate-ember-global.md might be the cause. But it supprise me that this breaking changes should not be until 4.0

**Comment by tythewebguy** [comment]
@ptgamr did you ever find a solution to this? I'm running into the same thing upgrading from Ember 3.24 to 3.28.

**Comment by artzte** [comment]
In my app, I just removed this package entirely... see https://github.com/TinyALE/tiny-ale/blob/develop/ui/app/components/modal-dialog.js and related files for one possible lightweight solution.

**Comment by tythewebguy** [comment]
Turns out the problem I ran into was actually an older version of `ember-moment` that used `ember-macro-helpers`, which is the add-on that was really breaking Ember 3.27. It was all being rendered within `ember-modal-dialog`, so the error messages were misleading.

`ember-macro-helpers` is no longer supported and the author says it's now deprecated. Took a while to uncover that mess.

**Comment by JackHowa** [comment]
this worked for me -- thanks @tythewebguy !
