### ISSUE TITLE
Enter KeyboardEvent

### ISSUE THREAD

**Issue by jrowlingson** [yapplabs/ember-modal-dialog#67]
Pressing the enter key causes the close action to send. What is the suggested way to send an alternate action for this keyboard event?

**Comment by lukemelia** [comment]
ember-modal-dialog doesn't do anything in particular with keyboard events out of the box. Our demo page (http://yapplabs.github.io/ember-modal-dialog/) exhibits similar behavior to what you are describing because the `button` that appears in the dialog is triggered by the enter key based on browser behavior.

**Comment by jrowlingson** [comment]
Ah. Got it - thanks!
