### ISSUE TITLE
alignment properties don't seem to make a difference

### ISSUE THREAD

**Issue by chrisolsen** [yapplabs/ember-modal-dialog#98]
The code below always positions the modal in the middle/center of the screen. I'm using v0.8.2
```
{{#modal-dialog
    target='body'
    attachment='top center'
    targetAttachment='top center'}}
  {{yield}}
{{/modal-dialog}}
```

**Comment by chrislopresto** [comment]
@chrisolsen This is a confusing artifact of unifying older and newer versions of this addon's components under a single API. 

The short explanation is that the `tether-dialog` component respects values like `top center` but the `modal-dialog` component only understands values like `center`. So in your example, `top center` is silently being cast to `center` with this code: https://github.com/yapplabs/ember-modal-dialog/blob/095970d5b9f0bb335a9f5db6a3a047df311dcee2/addon/components/positioned-container.js#L57-L58

This isn't ideal, and we would accept PRs to improve this behavior of our hand-rolled positioned container component. We haven't prioritized this work ourselves because the `ember-tether`-powered `tether-dialog` component provides far more capable positioning (and re-positioning).

The README attempts to explain all of this here:
- https://github.com/yapplabs/ember-modal-dialog#positioning-modal-dialog-components
- https://github.com/yapplabs/ember-modal-dialog#positioning-tether-dialog-components

Hope this helps. Closing this issue.
